export const ADD_PERSONNEL = "ADD_PERSONNEL";
export const EDIT_PERSONNEL = "EDIT_PERSONNEL";
export const DELETE_PERSONNEL = "DELETE_PERSONNEL";
export const SEARCH_PERSONNEL = "SEARCH_PERSONNEL";
export const ADD_CONGES = "ADD_CONGES";
export const VALID_CONGES = "VALID_CONGES";
