export const AuthPersonData = [ 
    { "id": "74f5936e-0917-49e8-bef7-da0e56442f28", "type": "Testing", "mode": "Manual", "site": "River", "handover_Reference": "Certificate_Testing_Handover8", "authorized_Person": "Tom Adena", "contractor": "Andy Aleby1", "contractor_Representative": null, "site_Location": "", "equipments": "Sewage Pump", "access_Arrangements": "", "work_Description": "Sewage Pump should be Cleaned.", "commence_Date": "2024-01-05", "completion_Date": "2025-06-30", "isInspectionUnderTaken": "Yes", "isStartOnSiteLetter": "Yes", "isHealthNSaftey": "Yes", "handover_Name": "", "takeover_Name": "", "handover_Date": "", "handover_Comment": "", "handback_Name": "", "takeback_Name": "", "handback_Date": "", "handback_Comment": "", "createdOn": "12-12-2023 08:03:13 AM", "createdBy": "Paul Anderson", "updatedOn": "", "updatedBy": "", "isActive": "True", "status": "New" },
    { "id": "f77885ea-bee6-4a0c-9148-cf0af2fb6d4f", "type": "Testing", "mode": "Manual", "site": "River", "handover_Reference": "Certificate_Testing_Handover7", "authorized_Person": "Tom Adena", "contractor": "Andy Aleby", "contractor_Representative": null, "site_Location": "", "equipments": "Water Reservoir", "access_Arrangements": "", "work_Description": "Water Reservoir should be Built.", "commence_Date": "2024-01-05", "completion_Date": "2025-06-30", "isInspectionUnderTaken": "Yes", "isStartOnSiteLetter": "Yes", "isHealthNSaftey": "Yes", "handover_Name": "", "takeover_Name": "", "handover_Date": "12-12-2023", "handover_Comment": "Water Reservoir work can be started", "handback_Name": "", "takeback_Name": "", "handback_Date": "", "handback_Comment": "", "createdOn": "12-12-2023 07:59:20 AM", "createdBy": "Tom Adena", "updatedOn": "", "updatedBy": "", "isActive": "True", "status": "New" },
    { "id": "096d8d02-0fbd-413c-9405-c764f154c709", "type": "Testing", "mode": "Manual", "site": "river", "handover_Reference": "Certificate_Testing_Handover3", "authorized_Person": "Tom Adena", "contractor": "Andy Aleby", "contractor_Representative": null, "site_Location": "", "equipments": "Water Reservoir", "access_Arrangements": "", "work_Description": "Water Reservoir should be repaired.", "commence_Date": "2024-02-15", "completion_Date": "2024-12-10", "isInspectionUnderTaken": "yes", "isStartOnSiteLetter": "Yes", "isHealthNSaftey": "Yes", "handover_Name": "", "takeover_Name": "", "handover_Date": "", "handover_Comment": "", "handback_Name": "", "takeback_Name": "", "handback_Date": "", "handback_Comment": "", "createdOn": "12-12-2023 07:51:20 AM", "createdBy": "Tom Adena", "updatedOn": "", "updatedBy": "", "isActive": "True", "status": "New" }
    ];

export const ContractorPersonData = [
    {
      "id": "74f5936e-0917-49e8-bef7-da0e56442f28",
      "type": "Testing",
      "mode": "Manual",
      "site": "River",
      "handover_Reference": "Certificate_Testing_Handover8",
      "authorized_Person": "Tom Adena",
      "contractor": "Andy Aleby",
      "contractor_Representative": null,
      "site_Location": "",
      "equipments": "Sewage Pump",
      "access_Arrangements": "",
      "work_Description": "Sewage Pump should be Cleaned.",
      "commence_Date": "2024-01-05",
      "completion_Date": "2025-06-30",
      "isInspectionUnderTaken": "Yes",
      "isStartOnSiteLetter": "Yes",
      "isHealthNSaftey": "Yes",
      "handover_Name": "",
      "takeover_Name": "",
      "handover_Date": "",
      "handover_Comment": "",
      "handback_Name": "",
      "takeback_Name": "",
      "handback_Date": "",
      "handback_Comment": "",
      "createdOn": "12-12-2023 08:03:13 AM",
      "createdBy": "Paul Anderson",
      "updatedOn": "",
      "updatedBy": "",
      "isActive": "True",
      "status": "New"
    },
    {
      "id": "f77885ea-bee6-4a0c-9148-cf0af2fb6d4f",
      "type": "Testing",
      "mode": "Manual",
      "site": "River",
      "handover_Reference": "Certificate_Testing_Handover7",
      "authorized_Person": "Tom Adena",
      "contractor": "Andy Aleby",
      "contractor_Representative": null,
      "site_Location": "",
      "equipments": "Water Reservoir",
      "access_Arrangements": "",
      "work_Description": "Water Reservoir should be Built.",
      "commence_Date": "2024-01-05",
      "completion_Date": "2025-06-30",
      "isInspectionUnderTaken": "Yes",
      "isStartOnSiteLetter": "Yes",
      "isHealthNSaftey": "Yes",
      "handover_Name": "",
      "takeover_Name": "",
      "handover_Date": "12-12-2023",
      "handover_Comment": "Water Reservoir work can be started",
      "handback_Name": "",
      "takeback_Name": "",
      "handback_Date": "",
      "handback_Comment": "",
      "createdOn": "12-12-2023 07:59:20 AM",
      "createdBy": "Tom Adena",
      "updatedOn": "",
      "updatedBy": "",
      "isActive": "True",
      "status": "New"
    },
    {
      "id": "50c7a98a-97d9-41b7-b0db-ef8b16ffbde7",
      "type": "Testing",
      "mode": "Handover",
      "site": "River",
      "handover_Reference": "Certificate_Testing_Handover5",
      "authorized_Person": "Kavin Cristopher",
      "contractor": "Andy Aleby",
      "contractor_Representative": null,
      "site_Location": "",
      "equipments": "Water Reservoir",
      "access_Arrangements": "",
      "work_Description": "Water Reservoir should be Built.",
      "commence_Date": "2024-01-05",
      "completion_Date": "2025-09-10",
      "isInspectionUnderTaken": "Yes",
      "isStartOnSiteLetter": "Yes",
      "isHealthNSaftey": "Yes",
      "handover_Name": "",
      "takeover_Name": "",
      "handover_Date": "",
      "handover_Comment": "",
      "handback_Name": "",
      "takeback_Name": "",
      "handback_Date": "",
      "handback_Comment": "",
      "createdOn": "12-12-2023 07:55:28 AM",
      "createdBy": "Tom Adena",
      "updatedOn": "",
      "updatedBy": "",
      "isActive": "True",
      "status": "New"
    },
    {
      "id": "93315f7d-e8fa-4cfe-aae2-648d11fa5935",
      "type": "Testing",
      "mode": "Manual",
      "site": "River",
      "handover_Reference": "Certificate_Testing_Handover4",
      "authorized_Person": "Kavin Cristopher",
      "contractor": "Andy Aleby",
      "contractor_Representative": null,
      "site_Location": "",
      "equipments": "Water Reservoir",
      "access_Arrangements": "",
      "work_Description": "Water Reservoir should be repaired.",
      "commence_Date": "2024-02-05",
      "completion_Date": "2024-10-10",
      "isInspectionUnderTaken": "yes",
      "isStartOnSiteLetter": "Yes",
      "isHealthNSaftey": "Yes",
      "handover_Name": "",
      "takeover_Name": "",
      "handover_Date": "",
      "handover_Comment": "",
      "handback_Name": "",
      "takeback_Name": "",
      "handback_Date": "",
      "handback_Comment": "",
      "createdOn": "12-12-2023 07:53:34 AM",
      "createdBy": "Tom Adena",
      "updatedOn": "",
      "updatedBy": "",
      "isActive": "True",
      "status": "New"
    },
    {
      "id": "096d8d02-0fbd-413c-9405-c764f154c709",
      "type": "Testing",
      "mode": "Manual",
      "site": "river",
      "handover_Reference": "Certificate_Testing_Handover3",
      "authorized_Person": "Tom Adena",
      "contractor": "Andy Aleby",
      "contractor_Representative": null,
      "site_Location": "",
      "equipments": "Water Reservoir",
      "access_Arrangements": "",
      "work_Description": "Water Reservoir should be repaired.",
      "commence_Date": "2024-02-15",
      "completion_Date": "2024-12-10",
      "isInspectionUnderTaken": "yes",
      "isStartOnSiteLetter": "Yes",
      "isHealthNSaftey": "Yes",
      "handover_Name": "",
      "takeover_Name": "",
      "handover_Date": "",
      "handover_Comment": "",
      "handback_Name": "",
      "takeback_Name": "",
      "handback_Date": "",
      "handback_Comment": "",
      "createdOn": "12-12-2023 07:51:20 AM",
      "createdBy": "Tom Adena",
      "updatedOn": "",
      "updatedBy": "",
      "isActive": "True",
      "status": "New"
    },
    {
      "id": "db00c22e-1cc3-4ae7-8e75-1cfdd2fddf72",
      "type": "Testing",
      "mode": "cert",
      "site": "river",
      "handover_Reference": "Certificate_Testing_Handover2",
      "authorized_Person": "John Devid",
      "contractor": "Andy Aleby",
      "contractor_Representative": null,
      "site_Location": "",
      "equipments": "Water Reservoir",
      "access_Arrangements": "",
      "work_Description": "Water Reservoir should be repaired.",
      "commence_Date": "2024-01-15",
      "completion_Date": "2024-11-15",
      "isInspectionUnderTaken": "yes",
      "isStartOnSiteLetter": "Yes",
      "isHealthNSaftey": "Yes",
      "handover_Name": "",
      "takeover_Name": "",
      "handover_Date": "",
      "handover_Comment": "",
      "handback_Name": "",
      "takeback_Name": "",
      "handback_Date": "",
      "handback_Comment": "",
      "createdOn": "12-12-2023 07:50:10 AM",
      "createdBy": "Tom Adena",
      "updatedOn": "",
      "updatedBy": "",
      "isActive": "True",
      "status": "New"
    },
    {
      "id": "fc6fd7d5-9138-4e28-8c3b-781a2bbe3532",
      "type": "Testing",
      "mode": "cert",
      "site": "river",
      "handover_Reference": "Certificate_Testing_Handover6",
      "authorized_Person": "John Scamans",
      "contractor": "",
      "contractor_Representative": null,
      "site_Location": "",
      "equipments": "test Equips",
      "access_Arrangements": "string",
      "work_Description": "Dam should be built.",
      "commence_Date": "2024-01-10",
      "completion_Date": "2024-12-15",
      "isInspectionUnderTaken": "yes",
      "isStartOnSiteLetter": "Yes",
      "isHealthNSaftey": "Yes",
      "handover_Name": "",
      "takeover_Name": "",
      "handover_Date": "",
      "handover_Comment": "",
      "handback_Name": "",
      "takeback_Name": "",
      "handback_Date": "",
      "handback_Comment": "",
      "createdOn": "11-12-2023 07:29:40 AM",
      "createdBy": "Test User",
      "updatedOn": "",
      "updatedBy": "",
      "isActive": "True",
      "status": "New"
    },
    {
      "id": "d1f4ae49-d149-4b42-a45e-371381bb3610",
      "type": "Testing",
      "mode": "Manual",
      "site": "River",
      "handover_Reference": "Certificate_Testing_Handover",
      "authorized_Person": "Jhon Kevin",
      "contractor": "",
      "contractor_Representative": null,
      "site_Location": "",
      "equipments": "",
      "access_Arrangements": "",
      "work_Description": "Dam needs to be repaired",
      "commence_Date": "2023-12-15",
      "completion_Date": "2024-06-30",
      "isInspectionUnderTaken": "Yes",
      "isStartOnSiteLetter": "Yes",
      "isHealthNSaftey": "Yes",
      "handover_Name": "",
      "takeover_Name": "",
      "handover_Date": "",
      "handover_Comment": "",
      "handback_Name": "",
      "takeback_Name": "",
      "handback_Date": "",
      "handback_Comment": "",
      "createdOn": "08-12-2023 07:07:51 AM",
      "createdBy": "Test User",
      "updatedOn": "",
      "updatedBy": "",
      "isActive": "True",
      "status": "New"
    }
  ];

export const IsDataFromAPI = [ {"flag" : true }];

export const AuthUserDetails = [
    {
      "id": "1001",
      "name": "Steven Carbtree",
      "role": "Authorized Person",
      "company": "Yorkshire Water",
      "mobileNumber": "9871233455"
    },
    {
      "id": "1002",
      "name": "Paul Anderson",
      "role": "Authorized Person",
      "company": "Yorkshire Water",
      "mobileNumber": "7654320987"
    },
    {
      "id": "1003",
      "name": "Tom Adena",
      "role": "Authorized Person",
      "company": "Yorkshire Water",
      "mobileNumber": "7654320900"
    },
    {
      "id": "1004",
      "name": "Jason Alred",
      "role": "Authorized Person",
      "company": "Yorkshire Water",
      "mobileNumber": "2234320900"
    }
  ];

export const ContractorUserDetails = [ { "id": "1005", "name": "Andy Aleby", "role": "Contractor", "company": "Jacobs Field Service Ltd", "mobileNumber": "2555678219" } ];

export const Sites = [ 
    { "siteId": "SAJ00123450", "name": "HUTTON LE HOLE/STW", "address": "Hutton Lane, North Yorkshire, S16" }, 
    { "siteId": "SAJ00230924", "name": "ABBEY ROAD/NO 1 SPS", "address": "Abbey Road, Yorkshire S17" }, 
    { "siteId": "SAJ00230931", "name": "ABBEY ROAD/NO 2 SPS", "address": "Abbey Road, KNAR, Yorkshire" }, 
    { "siteId": "SAJ00260519", "name": "ABBEYDALE ROAD 62/2 CSO", "address": "Abbeydale Road, Ilkley LS29 9QE, Yorkshire" }, 
    { "siteId": "SAJ00390507", "name": "ABBOTS RD SELBY SEWERAGE - WN - ABBOTS RD SELBY", "address": "ABBOTS ROAD, Whitby, YO22 4EB" } 
];

export const EquipmentDetails = [  
        {    "id": 101,    "name": "Sewage Pump",    "description": "Yorkshire Sewage Pumping Station"  }, 
        {    "id": 102,    "name": "Water Reservoir",    "description": "Yorkshire Water Reservoir Station" },
        {    "id": 103,    "name": "Water Motor", "description": "Yorkshire Water heavy motor" }
    ];

export const Certificates = [ 
    { "id": "74f5936e-0917-49e8-bef7-da0e56442f28", "type": "Testing", "mode": "Manual", "site": "River", "handover_Reference": "Certificate_Testing_Handover8", "authorized_Person": "Tom Adena", "contractor": "Andy Aleby", "contractor_Representative": null, "site_Location": "", "equipments": "Sewage Pump", "access_Arrangements": "", "work_Description": "Sewage Pump should be Cleaned.", "commence_Date": "2024-01-05", "completion_Date": "2025-06-30", "isInspectionUnderTaken": "Yes", "isStartOnSiteLetter": "Yes", "isHealthNSaftey": "Yes", "handover_Name": "", "takeover_Name": "", "handover_Date": "", "handover_Comment": "", "handback_Name": "", "takeback_Name": "", "handback_Date": "", "handback_Comment": "", "createdOn": "12-12-2023 08:03:13 AM", "createdBy": "Paul Anderson", "updatedOn": "", "updatedBy": "", "isActive": "True", "status": "New" }, 
    { "id": "f77885ea-bee6-4a0c-9148-cf0af2fb6d4f", "type": "Testing", "mode": "Manual", "site": "River", "handover_Reference": "Certificate_Testing_Handover7", "authorized_Person": "Tom Adena", "contractor": "Andy Aleby", "contractor_Representative": null, "site_Location": "", "equipments": "Water Reservoir", "access_Arrangements": "", "work_Description": "Water Reservoir should be Built.", "commence_Date": "2024-01-05", "completion_Date": "2025-06-30", "isInspectionUnderTaken": "Yes", "isStartOnSiteLetter": "Yes", "isHealthNSaftey": "Yes", "handover_Name": "", "takeover_Name": "", "handover_Date": "12-12-2023", "handover_Comment": "Water Reservoir work can be started", "handback_Name": "", "takeback_Name": "", "handback_Date": "", "handback_Comment": "", "createdOn": "12-12-2023 07:59:20 AM", "createdBy": "Tom Adena", "updatedOn": "", "updatedBy": "", "isActive": "True", "status": "New" }, 
    { "id": "50c7a98a-97d9-41b7-b0db-ef8b16ffbde7", "type": "Testing", "mode": "Handover", "site": "River", "handover_Reference": "Certificate_Testing_Handover5", "authorized_Person": "Kavin Cristopher", "contractor": "Andy Aleby", "contractor_Representative": null, "site_Location": "", "equipments": "Water Reservoir", "access_Arrangements": "", "work_Description": "Water Reservoir should be Built.", "commence_Date": "2024-01-05", "completion_Date": "2025-09-10", "isInspectionUnderTaken": "Yes", "isStartOnSiteLetter": "Yes", "isHealthNSaftey": "Yes", "handover_Name": "", "takeover_Name": "", "handover_Date": "", "handover_Comment": "", "handback_Name": "", "takeback_Name": "", "handback_Date": "", "handback_Comment": "", "createdOn": "12-12-2023 07:55:28 AM", "createdBy": "Tom Adena", "updatedOn": "", "updatedBy": "", "isActive": "True", "status": "New" }, 
    { "id": "93315f7d-e8fa-4cfe-aae2-648d11fa5935", "type": "Testing", "mode": "Manual", "site": "River", "handover_Reference": "Certificate_Testing_Handover4", "authorized_Person": "Kavin Cristopher", "contractor": "Andy Aleby", "contractor_Representative": null, "site_Location": "", "equipments": "Water Reservoir", "access_Arrangements": "", "work_Description": "Water Reservoir should be repaired.", "commence_Date": "2024-02-05", "completion_Date": "2024-10-10", "isInspectionUnderTaken": "yes", "isStartOnSiteLetter": "Yes", "isHealthNSaftey": "Yes", "handover_Name": "", "takeover_Name": "", "handover_Date": "", "handover_Comment": "", "handback_Name": "", "takeback_Name": "", "handback_Date": "", "handback_Comment": "", "createdOn": "12-12-2023 07:53:34 AM", "createdBy": "Tom Adena", "updatedOn": "", "updatedBy": "", "isActive": "True", "status": "New" }, 
    { "id": "096d8d02-0fbd-413c-9405-c764f154c709", "type": "Testing", "mode": "Manual", "site": "river", "handover_Reference": "Certificate_Testing_Handover3", "authorized_Person": "Tom Adena", "contractor": "Andy Aleby", "contractor_Representative": null, "site_Location": "", "equipments": "Water Reservoir", "access_Arrangements": "", "work_Description": "Water Reservoir should be repaired.", "commence_Date": "2024-02-15", "completion_Date": "2024-12-10", "isInspectionUnderTaken": "yes", "isStartOnSiteLetter": "Yes", "isHealthNSaftey": "Yes", "handover_Name": "", "takeover_Name": "", "handover_Date": "", "handover_Comment": "", "handback_Name": "", "takeback_Name": "", "handback_Date": "", "handback_Comment": "", "createdOn": "12-12-2023 07:51:20 AM", "createdBy": "Tom Adena", "updatedOn": "", "updatedBy": "", "isActive": "True", "status": "New" },
     { "id": "db00c22e-1cc3-4ae7-8e75-1cfdd2fddf72", "type": "Testing", "mode": "cert", "site": "river", "handover_Reference": "Certificate_Testing_Handover2", "authorized_Person": "John Devid", "contractor": "Andy Aleby", "contractor_Representative": null, "site_Location": "", "equipments": "Water Reservoir", "access_Arrangements": "", "work_Description": "Water Reservoir should be repaired.", "commence_Date": "2024-01-15", "completion_Date": "2024-11-15", "isInspectionUnderTaken": "yes", "isStartOnSiteLetter": "Yes", "isHealthNSaftey": "Yes", "handover_Name": "", "takeover_Name": "", "handover_Date": "", "handover_Comment": "", "handback_Name": "", "takeback_Name": "", "handback_Date": "", "handback_Comment": "", "createdOn": "12-12-2023 07:50:10 AM", "createdBy": "Tom Adena", "updatedOn": "", "updatedBy": "", "isActive": "True", "status": "New" }, 
     { "id": "fc6fd7d5-9138-4e28-8c3b-781a2bbe3532", "type": "Testing", "mode": "cert", "site": "river", "handover_Reference": "Certificate_Testing_Handover6", "authorized_Person": "John Scamans", "contractor": "", "contractor_Representative": null, "site_Location": "", "equipments": "test Equips", "access_Arrangements": "string", "work_Description": "Dam should be built.", "commence_Date": "2024-01-10", "completion_Date": "2024-12-15", "isInspectionUnderTaken": "yes", "isStartOnSiteLetter": "Yes", "isHealthNSaftey": "Yes", "handover_Name": "", "takeover_Name": "", "handover_Date": "", "handover_Comment": "", "handback_Name": "", "takeback_Name": "", "handback_Date": "", "handback_Comment": "", "createdOn": "11-12-2023 07:29:40 AM", "createdBy": "Test User", "updatedOn": "", "updatedBy": "", "isActive": "True", "status": "New" }, { "id": "d1f4ae49-d149-4b42-a45e-371381bb3610", "type": "Testing", "mode": "Manual", "site": "River", "handover_Reference": "Certificate_Testing_Handover", "authorized_Person": "Jhon Kevin", "contractor": "", "contractor_Representative": null, "site_Location": "", "equipments": "", "access_Arrangements": "", "work_Description": "Dam needs to be repaired", "commence_Date": "2023-12-15", "completion_Date": "2024-06-30", "isInspectionUnderTaken": "Yes", "isStartOnSiteLetter": "Yes", "isHealthNSaftey": "Yes", "handover_Name": "", "takeover_Name": "", "handover_Date": "", "handover_Comment": "", "handback_Name": "", "takeback_Name": "", "handback_Date": "", "handback_Comment": "", "createdOn": "08-12-2023 07:07:51 AM", "createdBy": "Test User", "updatedOn": "", "updatedBy": "", "isActive": "True", "status": "New" } ];